[tasks.backend-dev]
workspace = false
env = { RUST_LOG="info" }
command = "cargo"
args = ["watch", "-x", "'run'"]

[tasks.frontend-dev]
workspace = false
cwd = "./frontend"
command = "pnpm"
args = ["run", "dev"]

[tasks.backend]
workspace = false
env = { RUST_LOG="info" }
command = "cargo"
args = ["run"]

[tasks.frontend]
workspace = false
cwd = "./frontend"
command = "pnpm"
args = ["run"]

[tasks.clippy]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.format]
clear = true
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]